### ISSUE TITLE
HTTP2 pipeline is configured too early

### ISSUE THREAD

**Issue by glbrntt** [kylebrowning/swift-nio-http2-apns#10]
I think you have a bug here:

https://github.com/kylebrowning/swift-nio-http2-apns/blob/4fa6353d29ac7eb0fe5ad3656ba04ee1eda8ea87/Sources/NIOAPNS/APNSConnection.swift#L18

If the connection to the first initialized channel fails then you'll capture the wrong multiplexer instance (because the happy eyeballs connector will call the `channelInitializer` multiple times).

Moving the call to `configureHTTP2Pipeline` to a callback once you have a connection should fix it up!

**Comment by kylebrowning** [comment]
@glbrntt 
```
        return bootstrap.connect(host: configuration.url.host!, port: 443).flatMap { channel in
            return channel.pipeline.context(handlerType: HTTP2StreamMultiplexer.self).map { $0.handler as! HTTP2StreamMultiplexer }.flatMap { multiplexer in
                return multiplexerPromise.futureResult.map { multiplexer in
                    return APNSConnection(channel: channel, multiplexer: multiplexer, configuration: configuration)
                }
            }
        }
```

Something like that?

**Comment by glbrntt** [comment]
Not what I was thinking but that works too!

**Comment by kylebrowning** [comment]
Feel free to open a PR if you have a cleaner way!  

Though this will probably be fixed upstream in NIOHTTP2
